"""Add meta_title column to posts table

Revision ID: 6e73f887c080
Revises: dd4568bbf8f6
Create Date: 2025-09-12 18:20:28.309402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e73f887c080'
down_revision: Union[str, Sequence[str], None] = 'dd4568bbf8f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('meta_title', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'meta_title')
    # ### end Alembic commands ###
