"""Add post_content

Revision ID: 705105302e06
Revises: 3c81e6c3abe1
Create Date: 2025-08-30 14:21:23.880305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '705105302e06'
down_revision: Union[str, Sequence[str], None] = '3c81e6c3abe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_content')
    # ### end Alembic commands ###
