"""Add slug table to posts

Revision ID: 7085c0c5e405
Revises: 6e73f887c080
Create Date: 2025-09-13 21:40:11.519000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import re


# revision identifiers, used by Alembic.
revision: str = '7085c0c5e405'
down_revision: Union[str, Sequence[str], None] = '6e73f887c080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


posts_table = sa.table('posts',
    sa.column('id', sa.Integer),
    sa.column('title', sa.String),
    sa.column('slug', sa.String)
)


def slugify(text):
    """A simple function to create a URL-friendly slug."""
    text = text.lower()
    text = re.sub(r'[\s_]+', '-', text) # Replace spaces and underscores with hyphens
    text = re.sub(r'[^a-z0-9-]', '', text) # Remove non-alphanumeric characters except hyphens
    return text


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=False)
    # ### end Alembic commands ###

    # --- Data Migration: Populate slugs for existing posts ---
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)

    for post in session.query(posts_table).all():
        post_slug = slugify(post.title)
        session.execute(
            posts_table.update().where(posts_table.c.id == post.id).values(slug=post_slug)
        )

    session.commit()

    # Now, alter the column to be non-nullable
    op.alter_column('posts', 'slug', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
