"""Add slug table to posts

Revision ID: 7085c0c5e405
Revises: 6e73f887c080
Create Date: 2025-09-13 21:40:11.519000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7085c0c5e405'
down_revision: Union[str, Sequence[str], None] = '6e73f887c080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
